yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
handler403csrf = 'core.views.csrf_failure'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
Group = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=40)
    description = models.TextField(max_length=400)

    class Meta:
        verbose_name = 'Заголовок группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post, blank=True, null=True,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    def __str__(self):
        return str(self.user.username)

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post, Comment, Follow


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        labels = {
            'text': 'Текст',
            'group': 'Группа',
            'image': 'Картинка',
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст',
        }


class FollowForm(ModelForm):
    class Meta:
        model = Follow
        fields = ('author',)
        labels = {
            'author': 'Пользователь',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .models import Follow, Group, Post, User
from .forms import CommentForm, PostForm

POSTS_COUNT = 10


def get_page_context(request, queryset):
    paginator = Paginator(queryset, POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {
        'paginator': paginator,
        'page_number': page_number,
        'page_obj': page_obj,
    }


@cache_page(20 * 15)
def index(request):
    context = get_page_context(request, Post.objects.all())
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    context = {
        'group': group,
    }
    context.update(get_page_context(request, group.posts.all()))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = (
        request.user.is_authenticated
        and author.following.filter(user=request.user).exists()
    )
    context = {
        'author': author,
        'following': following,
    }
    context.update(get_page_context(request, author.posts.all()))
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, id=post_id)
    author_posts_count = post.author.posts.count()
    context = {
        'post': post,
        'form': form,
        'author_posts_count': author_posts_count,
    }
    return render(request, 'posts/post_detail.html', context)


@cache_page(20 * 15)
@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', post.author.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    context = get_page_context(
        request,
        Post.objects.filter(author__following__user=request.user).all()
    )
    return render(request, 'posts/index.html', context)


@login_required
def profile_follow(request, username):
    following = get_object_or_404(User, username=username)
    if following != request.user:
        Follow.objects.get_or_create(user=request.user, author=following)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    following = get_object_or_404(User, username=username)
    follower = get_object_or_404(Follow, author=following, user=request.user)
    follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %} 
  {% if is_edit %}       
    Редактировать запись
  {% else %}      
    Добавить запись
  {% endif %}
{% endblock  %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
        {% if is_edit %}       
          Редактировать пост
        {% else %}      
          Новый пост
        {% endif %}
        </div>
        <div class="card-body">        
          {% load user_filters %}
          {% if form.errors %}
            {% for field in form %} 
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}                                
          <form method="post" enctype="multipart/form-data" action=
            {% if is_edit %}
              "{% url 'posts:post_edit' post.pk %}"
              {% else %} 
              "{% url 'posts:post_create' %}"
            {% endif %}>
            {% csrf_token %}
          {% for field in form %} 
            <div class="form-group row my-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              {{ field|addclass:'form-control' }} 
                {% if field.help_text %}
                  <small 
                     id="{{ field.id_for_label }}-help"
                     class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
            </div>
          {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}               
              </button> 
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock  %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}Подписки на авторов{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% load thumbnail %}
  <h1>{% block header %}Подписки на авторов{% endblock %}</h1>
  {% for post in page_obj %} 
    <strong>Пост номер {{ post.pk }}</strong>
    <br/><br/>
    <p>{{ post.text|linebreaksbr }}</p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <ul>
      <li>
        Автор: <a href="{% url 'posts:profile' post.author %}"> {{ post.author }}</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      <a href={% url 'posts:post_detail' post.pk %}> Подробнее</a>
    </ul>
    <hr>
    
    {% if not post.comments.all %}
      У этого поста еще нет комментариев
      <p><a href={% url 'posts:add_comment' post.pk %}> Оставить первый комментарий</a>
    {% else %}
    <strong>
      Комментарии:
    </strong>
      {% for comment in post.comments.all %}
        <p>
          {{ comment.date_added }}
        </p>
          {{ comment.text }}
      {% endfor %}
    {% endif %}
    {% if post.group %}
      <p><a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы "{{ post.group.title }}"</a></p>
    {% endif%}
    {% if user.is_authenticated and user == post.author %}
    <p>
      <a href={% url 'posts:post_edit' post.pk %}> Редактировать запись</a>
    </p>
    {% endif %}
    {% if not forloop.last %}<hr>
    {% endif %}
  {% endfor %}

  {% include 'includes/paginator.html' %}

{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Группа {{ group.title }} {% endblock %}
{% block content %}
{% load thumbnail %}
  <h1> {{ group.title }} </h1>
  <p> {{ group.description }} </p>
  {% for post in page_obj %}
  <article>
    {% include 'posts/includes/body.html' %} 
  </article>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif%}  
  {% if not forloop.last %} <hr> {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Последние обновления на сайте  {% endblock  %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% load thumbnail %}
  {% for post in page_obj %} 
    <strong>Пост номер {{ post.pk }}</strong>
    <br/><br/>
    <p>{{ post.text|linebreaksbr }}</p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <article>
      {% include 'posts/includes/body.html' %} 
    </article>
    <ul>
      <a href={% url 'posts:post_detail' post.pk %}> Подробнее</a>
    </ul>
    <hr>
    
    {% if not post.comments.all %}
      У этого поста еще нет комментариев
      <p><a href={% url 'posts:add_comment' post.pk %}> Оставить первый комментарий</a>
    {% else %}
    <strong>
      Комментарии:
    </strong>
      {% for comment in post.comments.all %}
        <p>
          {{ comment.date_added }}
        </p>
          {{ comment.text }}
      {% endfor %}
    {% endif %}
    {% if post.group %}
      <p><a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы "{{ post.group.title }}"</a></p>
    {% endif%}
    {% if user.is_authenticated and user == post.author %}
    <p>
      <a href={% url 'posts:post_edit' post.pk %}> Редактировать запись</a>
    </p>
    {% endif %}
    {% if not forloop.last %}<hr>
    {% endif %}
  {% endfor %}

  {% include 'includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Пост {{ post.author|truncatechars:30 }}  {% endblock  %}
{% block content %}
{% load thumbnail %} 
<p><h2>Подробнее о посте {{ post.pk }}</h2></p> 
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </li>
          {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span > {{ post.author.posts.count }} </span>
            </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "820x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p> {{ post.text }} </p>
      {% if user.is_authenticated %}
      {% if author == user %}
        <a class="btn btn-primary" href={% url 'posts:post_edit' post.pk %}>
          редактировать запись
        </a>
        {% load user_filters %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            <input type="hidden" name="csrfmiddlewaretoken" value="">      
            <div class="form-group mb-2">
              <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
              </textarea>
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
            {% csrf_token %}
          </form>
        </div>
      </div>
      <h4> Комментарии к посту: </h4>
      {% for comment in post.comments.all %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
      {{ comment.date_added }}
      <p>
        {{ comment.text }}
      </p>
        </div>
      </div> 
      {% endfor %} 
      {% endif %}
      {% endif %}
    </article>
  </div>     
</div>  

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Профайл пользователя {{ author }} {% endblock  %}
{% block content %}
{% load thumbnail %}

<div class="container py-5">        
  <h1>Все посты пользователя {{ username }} </h1>
  <h3>Всего постов: {{ post_counter }} </h3>
  <div class="h6 text-muted">
    Подписчиков: {{ author.following.count }}  <br />
    Подписан: {{ author.follower.count }}
  </div>
  {% if following %}
  
  <div class="mb-5">
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  </div>
  {% else %}
    {% if author == user %}
      Это ваша страница
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
   {% endif %}
</div>

{% for post in page_obj %}
<ul>
  <li>
    Автор: {{ author }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
<p>{{ post.text|linebreaksbr }}</p>
{% if post.group %}    
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы "{{ post.group.title }}"</a>
{% endif %}
      {% if not forloop.last %} <hr> {% endif %}
    </article>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}